# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayload.proto\"w\n\x05\x45vent\x12\x1d\n\x06header\x18\x01 \x01(\x0b\x32\r.Event.Header\x12\x0f\n\x07payload\x18\x02 \x01(\t\x1a>\n\x06Header\x12\r\n\x05token\x18\x01 \x01(\t\x12\x12\n\nevent_type\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"\'\n\rEventsWrapper\x12\x16\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x06.Eventb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payload_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_EVENT']._serialized_start=17
  _globals['_EVENT']._serialized_end=136
  _globals['_EVENT_HEADER']._serialized_start=74
  _globals['_EVENT_HEADER']._serialized_end=136
  _globals['_EVENTSWRAPPER']._serialized_start=138
  _globals['_EVENTSWRAPPER']._serialized_end=177
# @@protoc_insertion_point(module_scope)
